--  Courses
create table
  public.courses (
    id bigint generated by default as identity,
    name character varying null,
    department_id bigint null,
    constraint courses_pkey primary key (id),
    constraint courses_department_id_fkey foreign key (department_id) references departments (id) on delete set null
  ) tablespace pg_default;

-- Departments
create table
  public.departments (
    id bigint generated by default as identity,
    name character varying null,
    constraint department_pkey primary key (id)
  ) tablespace pg_default;
  
-- Institutions
create table
  public.institutions (
    id bigint generated by default as identity,
    name character varying null,
    constraint institutions_pkey primary key (id)
  ) tablespace pg_default;

-- Students
create table
  public.students (
    cpf bigint generated by default as identity,
    name character varying null,
    address character varying null,
    course_id bigint null,
    constraint student_pkey primary key (cpf),
    constraint students_course_id_fkey foreign key (course_id) references courses (id) on delete set null
  ) tablespace pg_default;

-- Teachers
create table
  public.teachers (
    cpf bigint generated by default as identity,
    name character varying null,
    institution_id integer null,
    department_id smallint null,
    constraint teachers_pkey primary key (cpf)
  ) tablespace pg_default;